name: server
description: A server app using the shelf package and Docker.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.6.0

dependencies:
  drift: ^2.23.0
  drift_postgres: ^1.3.0
  logging: ^1.3.0
  shelf: ^1.4.0
  shelf_router: ^1.1.0
  sqlite3: ^2.5.0

dev_dependencies:
  build_runner: ^2.4.14
  drift_dev: ^2.23.0
  http: ^1.1.0
  lints: ^5.0.0
  test: ^1.24.0
